apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-app
spec:
  selector:
    matchLabels:
      app: inventory-management-app
  replicas: 2
  template:
    metadata:
      labels:
        app: inventory-management-app
    spec:
      containers:
        - name: imsapp
          image: imscontainerregistryallegion.azurecr.io/inventorymanagement-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: ims-app-port