apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-app
spec:
  selector:
    matchLabels:
      app: inventory-management-app
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory-management-app
    spec:
      containers:
        - name: imsapp
          image: imscr.azurecr.io/inventory-management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081