apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-mgmnt-app
spec:
  selector:
    matchLabels:
      app: inventory-mgmnt-app
  replicas: 2
  template:
    metadata:
      labels:
        app: inventory-mgmnt-app
    spec:
      containers:
        - name: inventory-mgmnt-app
          image: inventorymanagement:latest
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management