apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-app
spec:
  selector:
    matchLabels:
      app: inventory-management-app
  replicas: 2
  template:
    metadata:
      labels:
        app: inventory-management-app
    spec:
      containers:
        - name: imsapp
          image: myvikasregistry.azurecr.io/sample/hello:9
          ports:
            - containerPort: 8081