apiVersion: v1
kind: Service
metadata:
  name: inventory-mgmnt-app
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
    - port: 8080
      targetPort: 8080
      name: management
  selector:
    app: inventory-mgmnt-app
