export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const PRODUCT_ASSIGN_LIST = "ASSIGNMENT_LIST";
export const LOGOFF = "LOGOFF";
export const LOGIN = "LOGIN";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const ENQUEUE_SNACKBAR = "ENQUEUE_SNACKBAR";
export const REMOVE_SNACKBAR = "REMOVE_SNACKBAR";
export const TOGGLE_SIDENAV = 'TOGGLE_SIDENAV';
export const BOOTSTRAP_APP = "BOOTSTRAP_APP";
export const SAVE_PROFILE = "SAVE_PROFILE";
export const SAVE_TEAMS = "SAVE_TEAMS";
export const ADD_TEAMS = "ADD_TEAMS";
export const SAVE_RESET_PASSWORD = "SAVE_RESET_PASSWORD";
export const SAVE_USERS="SAVE_USERS"

